//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDay1Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatogaryDetail
    {
        public int CatogaryDetails_ID { get; set; }
        public Nullable<int> CatogaryDetails_CatogeryID { get; set; }
        public string CatogaryDetails_Day { get; set; }
        public string CatogaryDetails_Time { get; set; }
        public Nullable<System.DateTime> CatogaryDetails_date { get; set; }
        public Nullable<bool> CatogaryDetails_Deletestatus { get; set; }
    
        public virtual Catogary Catogary { get; set; }
    }
}
