//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDay1Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catogary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Catogary()
        {
            this.CatogaryDetails = new HashSet<CatogaryDetail>();
            this.StudentCats = new HashSet<StudentCat>();
        }
    
        public int Catogary_ID { get; set; }
        public string Catogary_Name { get; set; }
        public Nullable<int> Catogary_StageID { get; set; }
        public Nullable<int> Catogary_SectionID { get; set; }
        public Nullable<decimal> Catogary_Cost { get; set; }
        public Nullable<int> Catogary_SubjectID { get; set; }
        public Nullable<int> Catogary_Empid { get; set; }
        public Nullable<System.DateTime> Catogary_DOC { get; set; }
        public Nullable<bool> Catogary_Deletestatus { get; set; }
        public Nullable<bool> Catogary_PayedWays { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatogaryDetail> CatogaryDetails { get; set; }
        public virtual Subject Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentCat> StudentCats { get; set; }
    }
}
