//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDay1Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpAttendance
    {
        public int EmpAttend_ID { get; set; }
        public Nullable<System.DateTime> EmpAttend_Date { get; set; }
        public Nullable<int> EmpAttend_EmpID { get; set; }
        public Nullable<bool> EmpAttend_Deletestatus { get; set; }
    }
}
