//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDay1Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpLeaf
    {
        public int EmpLeave_ID { get; set; }
        public Nullable<System.DateTime> EmpLeave_Date { get; set; }
        public Nullable<int> EmpLeave_EmpId { get; set; }
        public Nullable<bool> EmpLeave_DeleteStatus { get; set; }
    }
}
