//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDay1Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int Exams_ID { get; set; }
        public string Exams_Name { get; set; }
        public Nullable<decimal> Exams_highdegree { get; set; }
        public Nullable<decimal> Exams_Lowdegree { get; set; }
        public Nullable<bool> Exams_deleteStatus { get; set; }
    }
}
