//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDay1Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int Job_ID { get; set; }
        public string Job_name { get; set; }
        public string powers { get; set; }
        public bool Job_DeleteStatus { get; set; }
        public Nullable<int> Job_UserID { get; set; }
    }
}
