//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDay1Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewRegistration
    {
        public int NewRegistration_ID { get; set; }
        public Nullable<System.DateTime> NewRegistration_Date { get; set; }
        public Nullable<int> NewRegistration_StuID { get; set; }
        public Nullable<decimal> NewRegistration_Totalvalue { get; set; }
        public Nullable<decimal> NewRegistration_Discount { get; set; }
        public Nullable<decimal> NewRegistration_Netvalue { get; set; }
        public Nullable<decimal> NewRegistration_Paidvalue { get; set; }
        public Nullable<decimal> NewRegistration_Remaining { get; set; }
        public Nullable<int> NewRegistration_CashID { get; set; }
        public Nullable<bool> NewRegistration_DeleteStatus { get; set; }
    }
}
