//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDay1Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPenningValue
    {
        public int OPenningValues_ID { get; set; }
        public Nullable<int> OPenningValues_AccountID { get; set; }
        public string OPenningValues_Code { get; set; }
        public Nullable<bool> OPenningValues_Debit { get; set; }
        public Nullable<bool> OPenningValues_Credit { get; set; }
        public Nullable<decimal> OPenningValues_value { get; set; }
        public Nullable<System.DateTime> OPenningValues_Date { get; set; }
        public Nullable<bool> OPenningValues_DeleteStatus { get; set; }
    }
}
