//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDay1Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayCatExpnce
    {
        public int PayCatExpnces_ID { get; set; }
        public Nullable<int> PayCatExpnces_StuID { get; set; }
        public Nullable<int> PayCatExpnces_CatID { get; set; }
        public Nullable<decimal> PayCatExpnces_Discount { get; set; }
        public Nullable<decimal> PayCatExpnces_Value { get; set; }
        public Nullable<decimal> PayCatExpnces_NetValue { get; set; }
        public string PayCatExpnces_Nots { get; set; }
        public Nullable<int> PayCatExpnces_CashID { get; set; }
        public Nullable<System.DateTime> PayCatExpnces_DOP { get; set; }
        public Nullable<bool> PayCatExpnces_DeleteStatus { get; set; }
    }
}
