//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDay1Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.StudentCats = new HashSet<StudentCat>();
        }
    
        public int Student_ID { get; set; }
        public Nullable<int> Student_StageID { get; set; }
        public Nullable<int> Student_SectionID { get; set; }
        public string Student_Name { get; set; }
        public string Student_Address { get; set; }
        public string Student_School { get; set; }
        public string Student_Phone1 { get; set; }
        public string Student_Phone2 { get; set; }
        public string Student_Notes { get; set; }
        public Nullable<bool> Student_DeleteStatus { get; set; }
        public string Student_Barcode { get; set; }
        public Nullable<int> Student_CatID { get; set; }
        public Nullable<int> Student_Payedstatus { get; set; }
    
        public virtual Stage Stage { get; set; }
        public virtual Stage Stage1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentCat> StudentCats { get; set; }
    }
}
