//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDay1Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAttendance
    {
        public int StudentAttend_ID { get; set; }
        public Nullable<System.DateTime> StudentAttend_Date { get; set; }
        public Nullable<int> StudentAttend_StuID { get; set; }
        public Nullable<int> StudentAttend_CatID { get; set; }
        public string StudentAttend_Status { get; set; }
        public Nullable<bool> StudentAttend_Deletestatus { get; set; }
    }
}
