//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDay1Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentPaye
    {
        public int StudentPayes_ID { get; set; }
        public Nullable<int> StudentPayes_StuID { get; set; }
        public Nullable<int> StudentPayes_CatID { get; set; }
        public Nullable<System.DateTime> StudentPayes_Date { get; set; }
        public Nullable<decimal> StudentPayes_Totalvalue { get; set; }
        public Nullable<decimal> StudentPayes_CatCost { get; set; }
        public Nullable<decimal> StudentPayes_NotesEXp { get; set; }
        public decimal StudentPayes_Netvalue { get; set; }
        public Nullable<int> StudentPayes_PayStuType { get; set; }
        public string StudentPayes_PaysType { get; set; }
        public Nullable<int> StudentPayes_CashID { get; set; }
        public Nullable<bool> StudentPayes_Detestatus { get; set; }
    }
}
