//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDay1Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentLeaf
    {
        public int StudentLeave_ID { get; set; }
        public Nullable<System.DateTime> StudentLeave_date { get; set; }
        public Nullable<int> StudentLeave_StuID { get; set; }
        public Nullable<bool> StudentLeave_Deletestatus { get; set; }
    }
}
