//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDay1Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCat
    {
        public int StudentCat_ID { get; set; }
        public Nullable<int> StudentCat_StuID { get; set; }
        public Nullable<int> StudentCat_CatID { get; set; }
        public Nullable<System.DateTime> StudentCat_date { get; set; }
        public Nullable<bool> StudentCat_deletestatus { get; set; }
    
        public virtual Catogary Catogary { get; set; }
        public virtual Student Student { get; set; }
    }
}
