//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDay1Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentReturn
    {
        public int StudentReturn_ID { get; set; }
        public Nullable<System.DateTime> StudentReturn_Date { get; set; }
        public Nullable<int> StudentReturn_StuID { get; set; }
        public Nullable<int> StudentReturn_CashID { get; set; }
        public Nullable<decimal> StudentReturn_Remaining { get; set; }
        public Nullable<bool> StudentReturn_Satus { get; set; }
        public Nullable<bool> StudentReturn_DeletStaus { get; set; }
    }
}
